# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: CmdLine@2
  displayName: npx npm-force-resolutions
  inputs:
    script: |
      cd QuickApp/ClientApp
      npx npm-force-resolutions
      cd ..
      cd ..

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'
    workingDir: 'QuickApp/ClientApp'

- task: Npm@1
  displayName: npm run build
  inputs:
    command: 'custom'
    workingDir: 'QuickApp/ClientApp'
    customCommand: 'run build-prod'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'QuickApp/ClientApp/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'